_extends: action-test:.github/release-drafter.yml
name-template: 'Release: $WEBVIEW_NAME v$RESOLVED_VERSION'
tag-template: '$WEBVIEW_NAME-v$RESOLVED_VERSION'
tag-prefix: '$WEBVIEW_NAME-v'
include-paths:
  - 'webviews'
  - 'packages'
