_extends: action-test:.github/release-drafter.yml
name-template: 'Release: ${{ env.WEBVIEW_NAME }} v$RESOLVED_VERSION'
tag-template: '${{ env.WEBVIEW_NAME }}-v$RESOLVED_VERSION'
tag-prefix: '${{ env.WEBVIEW_NAME }}-v'
include-paths:
  - 'webviews'
  - 'packages'
