name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  webview:
      name: 'Release Drafter - webview'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3  
        
        - name: Parse tag into name & version
          run: |
            TAG=${GITHUB_REF#refs/tags/}
            # 'apply-v1.2.3' → NAME=apply, VERSION=1.2.3
            NAME=${TAG%-v*}
            VERSION=${TAG#*-v}
            
            echo "Extracted NAME: $NAME"
            echo "Extracted VERSION: $VERSION"

            echo "WEBVIEW_NAME=$NAME" >> $GITHUB_ENV
            echo "RESOLVED_VERSION=$VERSION" >> $GITHUB_ENV

        - name: Draft Release Notes
          uses: release-drafter/release-drafter@v5
          with:
            config-name: release-drafter-webview.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WEBVIEW_NAME: ${{ env.WEBVIEW_NAME }}
            
