name: Release Drafter

on:
  push:
    branches:
      - main
      - feat/mono-repo

jobs:
  mobile-seller:
    name: 'Release Drafter - mobile-seller'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter-mobile-seller.yml
  pc-seller:
    name: 'Release Drafter - pc-seller'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter-pc-seller.yml
  webview:
      name: 'Release Drafter - webview'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3  
        
        - name: Parse tag into name & version
          if: startsWith(github.ref, 'refs/tags/')
          run: |
            TAG=${GITHUB_REF#refs/tags/}
            # 'apply-v1.2.3' → NAME=apply, VERSION=1.2.3
            NAME=${TAG%-v*}
            VERSION=${TAG#*-v}

            echo "WEBVIEW_NAME=$NAME" >> $GITHUB_ENV
            echo "RESOLVED_VERSION=$VERSION" >> $GITHUB_ENV

        - name: Draft Release Notes
          uses: release-drafter/release-drafter@v5
          with:
            config-name: release-drafter-webview.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WEBVIEW_NAME: ${{ env.WEBVIEW_NAME }}
            
