name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  webview:
      name: 'Release Drafter - webview'
      runs-on: ubuntu-latest
      steps:
        - name: Draft Release Notes
          uses: release-drafter/release-drafter@v5
          with:
            config-name: release-drafter-webview.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WEBVIEW_NAME: 'webview test'
            
